### ISSUE TITLE
ApiHandler.Customer.Update fails with exception

### ISSUE THREAD

**Issue by philmoz** [Parature/ParatureSDK#21]
The following code generates an exception - "Invalid XML data: The element 'Customer_Role' has invalid child element 'Role'. List of possible elements expected: 'CustomerRole'."

    var customer = ApiHandler.Customer.GetDetails(customerId, creds);
    customer.Email = newEmail;
    var response = ParatureSDK.ApiHandler.Customer.Update(customer, creds);

I also get an exception (different message) if the Tou field on the customer record is not null.

Phil.

**Comment by brtubb** [comment]
Issue found and replicated. Problem was how we were serializing the CustomerRoleReference class. Fixed in master

**Comment by philmoz** [comment]
I still get an exception if the customer.Tou field is not null.

Exception - "Invalid XML data: The 'Tou' element is invalid - The value 'False' is invalid according to its datatype 'Union' - The value 'False' is not valid according to any of the memberTypes of the union."

**Comment by brtubb** [comment]
Reopening per Phil's exception details. Investigating

**Comment by brtubb** [comment]
@philmoz 
I was getting an invalid cast in the Tou property, but not an exception. Just pushed a fix for the invalid cast. This was for the GetDetails method. Are you using a different method?

When you get a chance, mind seeing if that still throws an exception on the deserialization?

**Comment by philmoz** [comment]
It's working correctly now - no exception in Customer.Update from the Tou field.

**Comment by brtubb** [comment]
Awesome, thank you! Closing this out.
